---
blueprint:
  name: Motion-activated Light
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/dsskcritser/ha-blueprints/blob/main/motion-light-override.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    override_switch:
      name: Override Switch
      description: What helper or switch can lock the automation out.
      selector:
        target:
          entity:
            domain: toggle,switch
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: motion_entity
  from: off
  to: on
condition:
  - condition: state
    entity_id: override_switch
    state: off
action:
  - alias: Turn on the light
    service: light.turn_on
    target: light_target
  - alias: Wait until there is no motion from device
    wait_for_trigger:
      platform: state
      entity_id: motion_entity
      from: on
      to: off
  - alias: Wait the number of seconds that has been set
    delay: no_motion_wait
  - alias: Turn off the light
    service: light.turn_off
    target: light_target
